#!/bin/bash
# This hook is run after this virtualenv is activated.

# Checks to see if we have already got a start_watchdog script running, if not
# creates a new one in a new terminal. 

already_running=$(ps -a|grep "start_watchdog")
if [ -z "$already_running" ]; then
    gnome-terminal -x /home/nigel/code/timefeed/start_watchdog
fi


