#!/bin/bash
# This hook is run after this virtualenv is activated.

# Checks to see if we have already got a start_watchdog script running, if not
# creates a new one in a new terminal. 

already_running=$(ps -a|grep "start_watchdog")
if [ -z "$already_running" ]; then
    cd /home/nigel/code/timefeed
    gnome-terminal -x ./start_watchdog
fi


